import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const Settings=require('../public/model-settings.js'), Selection=require('../public/runtime-selection-state.js');
const Gate=require('../public/runtime-capability-gate.js'), Runtime=require('../public/runtime-capabilities.js');
const Lifecycle=require('../public/model-import-lifecycle-domain.js');
const values=new Map(), storage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value)};
globalThis.localStorage=storage;
const sol={mode:'model',provider:'codex',model:'gpt-5.6-sol'}, ds={mode:'model',provider:'deepseek',model:'deepseek-flash'};
storage.setItem(Gate.CURRENT_RUNTIME_STORAGE_KEY,JSON.stringify(sol));
const chosen=(runtime,effort)=>({...runtime,execution_settings:Settings.envelope(runtime,effort?{reasoning_effort:effort}:{})});
assert.equal(Selection.resolve('candidate_conversation','a').execution_settings.effective_settings.reasoning_effort,'medium');
const oldRevision=Selection.version();
await Selection.update({scope:'a',runtime:chosen(sol,'low'),expectedRevision:oldRevision});
assert.equal(Selection.resolve('candidate_conversation','a').execution_settings.effective_settings.reasoning_effort,'low');
assert.equal(Selection.resolve('candidate_conversation','b').execution_settings.effective_settings.reasoning_effort,'medium');
await assert.rejects(()=>Selection.update({scope:'a',runtime:chosen(sol,'high'),expectedRevision:oldRevision}),/另一页面/);
const low=Runtime.createRuntimeSnapshot(Selection.resolve('candidate_conversation','a'),{modelDescriptor:Gate.modelDescriptorForRuntime(sol,'candidate_conversation')});
assert.ok(Object.isFrozen(low.execution_settings.effective_settings));
await Selection.update({scope:'b',runtime:chosen(sol,'high'),expectedRevision:Selection.version(),makeDefault:true});
assert.equal(Selection.resolve('candidate_conversation','a').execution_settings.effective_settings.reasoning_effort,'low');
assert.equal(Selection.resolve('job_conversation','c').execution_settings.effective_settings.reasoning_effort,'high');
Selection.assertCurrent(low,'candidate_conversation');
await Selection.update({scope:'a',clear:true,expectedRevision:Selection.version()});
assert.throws(()=>Selection.assertCurrent(low,'candidate_conversation'),/RUNTIME_SELECTION_CHANGED/);
const high=Runtime.createRuntimeSnapshot(Selection.resolve('candidate_conversation','a'),{modelDescriptor:Gate.modelDescriptorForRuntime(sol,'candidate_conversation')});
assert.notEqual(await Lifecycle.runtimeFingerprint(low),await Lifecycle.runtimeFingerprint(high));
assert.equal(await Lifecycle.runtimeFingerprint(high),await Lifecycle.runtimeFingerprint({...high,execution_settings:{...high.execution_settings,selection_revision:'other',scope:'another'}}));
assert.throws(()=>Settings.validate({...high.execution_settings,effective_settings:{reasoning_effort:'ultra'}},sol.provider,sol.model),/unsupported/);
assert.throws(()=>Settings.validate({...Settings.envelope(ds),effective_settings:{reasoning_effort:'high'}},ds.provider,ds.model),/invalid/);
assert.throws(()=>Settings.validate(high.execution_settings,ds.provider,ds.model),/mismatch/);
const legacy={...high};delete legacy.execution_settings;
assert.equal(Runtime.validateRuntimeSnapshot(legacy).execution_settings,undefined);
storage.setItem(Gate.CURRENT_RUNTIME_STORAGE_KEY,JSON.stringify({mode:'local'}));
assert.equal(Selection.resolve('candidate_conversation','a').mode,'local');
assert.throws(()=>Selection.assertCurrent(high,'candidate_conversation'));
storage.setItem(Gate.CURRENT_RUNTIME_STORAGE_KEY,JSON.stringify(sol));
storage.setItem(Gate.OPERATION_RUNTIME_STORAGE_KEY,JSON.stringify({job_conversation:ds}));
assert.equal(Selection.resolve('job_conversation','d').provider,'codex','old cross-provider preference cannot override homepage');
await Selection.update({scope:'d',clear:true,expectedRevision:Selection.version()});
assert.equal(Selection.resolve('job_conversation','d').provider,'codex');
assert.equal(Selection.resolve('job_conversation','untouched').provider,'codex');
await Selection.update({scope:'a',runtime:chosen(sol,'low'),expectedRevision:Selection.version()});
assert.equal(Selection.resolve('job_conversation','untouched').provider,'codex');
assert.equal(JSON.parse(storage.getItem(Gate.OPERATION_RUNTIME_STORAGE_KEY)).job_conversation.provider,'deepseek','preference retained but inactive across Providers');
await Selection.update({scope:'a',runtime:chosen(sol,'medium'),expectedRevision:Selection.version(),makeDefault:true});
assert.equal(Selection.resolve('job_conversation','d').provider,'codex');
globalThis.sessionStorage=storage;let confirmations=0;
globalThis.confirm=()=>{confirmations++;return true;};
const active=Selection.resolve('candidate_conversation','a');
await Selection.beforeDispatch(active,'candidate_conversation');await Selection.beforeDispatch(active,'candidate_conversation');
assert.equal(confirmations,1);
console.log('model_selection_scope_CAS_migration_settings_cache_consent=PASS');
// Runtime-provided qualified models keep scope, effort and consent identities separate.
const {execFileSync}=await import('node:child_process');
const entries=JSON.parse(execFileSync(process.env.ARIADNE_TEST_PYTHON||'python3',['-c','import json; from src.codex_models import settings_entries; print(json.dumps(settings_entries()))'],{encoding:'utf8'}));
Settings.refreshCodex(entries);
globalThis.AriadneProduct={kind:'skill',runtime:value=>value};
const luna={mode:'model',provider:'codex',model:'gpt-6-luna'};
await Selection.update({scope:'new-model',runtime:chosen(luna,'max'),expectedRevision:Selection.version()});
const selected=Selection.resolve('personal_understanding','new-model');
assert.equal(selected.model,luna.model);
assert.equal(selected.execution_settings.effective_settings.reasoning_effort,'max');
assert.equal(Selection.resolve('personal_understanding','different-scope').model,sol.model);
assert.equal(Gate.modelDescriptorForRuntime(luna,'job_conversation').model_id,luna.model);
assert.equal(Gate.isModelRuntimeEligible({...luna,model:'unqualified'}),false);
assert.throws(()=>Settings.validate(Settings.envelope({...luna,model:'gpt-5.5'},{reasoning_effort:'max'}),'codex','gpt-5.5'),/unsupported/);
await Selection.beforeDispatch(selected,'personal_understanding');
assert.equal(confirmations,2,'new model requires new consent');
console.log('dynamic_models_scope_effort_consent=PASS');
